### ISSUE TITLE
How get IP of others clients

### ISSUE THREAD

**Issue by oismaelash** [M-Aghasi/Unity-UdpSocket-BitStream-Utilities#2]
Hello,
How can I get the IP of the client that sent the message?
Regards,

**Comment by M-Aghasi** [comment]
Hi, with UDP we can send packets from one local port to any target ip/port and listen packets from any remote ip/port because UDP is stateless, but current version of UdpSocketManager has designed for client-server communications where you receive and send packets to a particular server (which in this case you set ip/port of destination server when you instantiate UdpSocketManager).

But it’s a good feature to allow setting destination ip/port for any packet we send and get ip/port for any packet we receive, so I will consider this use case for next versions.

**Comment by oismaelash** [comment]
My solution: https://github.com/IsmaelNascimento/Udp-for-Unity
